---

Parameters:
  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref AWS::StackName
      RetentionInDays: 90

  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Ref AWS::StackName

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and RDP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  ElasticIp:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref Ec2Instance

  Ec2Instance:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M
    Metadata:
      AWS::CloudFormation::Init:
        config:
          files:
            /minecraft-stuff/fuck.txt:
              content: fuck
              owner: root
              group: root
            /minecraft-stuff/server.jar:
              source: https://piston-data.mojang.com/v1/objects/7bf95409b0d9b5388bfea3704ec92012d273c14c/server.jar
              owner: root
              group: root
          commands:
            1_yo:
              command: echo 'Yo!'
              waitAfterCompletion: 0
    Properties:
      InstanceType: t3.small
      ImageId: !Ref ImageId
      SecurityGroups:
        - !Ref SecurityGroup
      KeyName: !Ref KeyPair
      Monitoring: true
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
      UserData:
        Fn::Base64:
          !Sub
          - |
            #!/bin/bash -x
            yum install -y aws-cfn-bootstrap
            /opt/aws/bin/cfn-init -v --stack ${stack_name} --resource Ec2Instance --region ${region}
            /opt/aws/bin/cfn-signal -e $? --stack ${stack_name} --resource Ec2Instance --region ${region}
          - stack_name: !Ref AWS::StackName
            region: !Ref AWS::Region
